import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Añade los idiomas y traducciones aquí
const resources = {
    en: {
      translation: {
        leading: "Leading",
        transform:"the transformation of ",
        talent2:"talent",
        parrapfPink:"We are committed to redefining standards in",
        rrhh: "human resources",
        diversity: " priorizung diversity",
        inclusion:" inclusion and ",
        talent:"talent development",
        fundamentals:"as fundamental pillars",
        mission:"Mission",
        mission2:"We are dedicated to designing and executing human resources strategies that value and promote diversity and inclusion. Our commitment is to the development of talent in its broadest expression, offering solutions that allow organizations and their teams to reach their maximum potential in a constantly evolving labor market.",
        vision:"Vision",
        vision2:"To become a global human resources firm that is synonymous with excellence, innovation and equity, setting the standard in creating inclusive and dynamic work environments that celebrate and enhance diversity in all its forms.",
        values:"Values",
        values2:"Our core values ​​include fairness, respect for diversity, integrity, innovation and collaboration promoting equal opportunities. We anticipate trends to offer cutting-edge services, and we work closely with our clients to drive positive change.",
        talent1:"Talents",
        companies:"Companies",
        femi:"FemInnova ",
        femi2:"innovation and quality in Talent management.",
        femi3:"Our company, driven by a bold vision, is committed to redefining standards in human resources, prioritizing diversity, inclusion and talent development as fundamental pillars.",
        femi4:"stands out as a reference for",
        discover:"Discover your potential with our specialized workshops  in",
        discover2:"talent development",
        sendCv: "Send CV",
        home: "HOME",
        services: "SERVICES",
        methodology: "WORK METHODOLOGY",
        contact: "CONTACT",
        workshops:"WORKSHOPS",
        methodology2:"Work methodology",
        mant:"We maintain a ",
        standard:"standard of excellence ",
        every:"in all our services, ensuring that each strategy is",
        align:"aligned with specific needs and objectives",
        client:" of our clients.",
        how:"How will we find your ideal candidate?",
        sourcing:"Sourcing",
        recolection:"Collection of the best profiles that fit what the client requests.",
        groupEn:"Group interview",
        selection:"Candidate selection",
        ofer:"Offer letter",
        screening:"Telephone screening",
        call:"Brief call to align interests and corroborate knowledge required for the position. ",
        entrev:"In-depth individual interview",
        presentation:"Client presentation",
        femContact:"At Feminnova , ",
        workHands:"we work hand in hand ",
        clientEquip:"with our clients and their teams, creating synergies that",
        positive:"drive positive change ",
        baseEqui:"based on equity, equality and diversity.",
        contactBotton:"Contact",
        homeFooter: "Home",
        sendCvFooter:"Send CV",
        client2:"Clients",
        servicesFooter:"Services",
        contactFooter:"Contact",
        workshopsFooter:"Workshops",
        sendFooter:"Send",
        workMethodologyFooter:"Work Methodology",
        reserved:"All rights reserved",
        preselection:"We invite shortlisted candidates to participate in group interviews, where we assess their ability to work as a team, communicate effectively and solve problems in a collaborative environment.",
        tecnics:"Based on the interviews and evaluations carried out, we select the most qualified and suitable candidates for the position, taking into account both their technical skills and their personal competencies.",
        help:"Once the client has selected the ideal candidate, we help in preparing the offer letter, facilitating the hiring process and ensuring a smooth transition towards the incorporation of the new employee.",
        start:"We conduct in-depth individual interviews using the START (Situation, Task, Action, Result) technique to delve deeper into candidates' experience and skills, as well as to assess their suitability for the position.",
        presentation2:"We present selected candidates to the client for review and final consideration, providing detailed information about each candidate and their suitability for the position.",
        services1: "Ready for a ",
      services2: "positive change",
      services3: " in ",
      services4: "talent management?",
      services5: "Our services",
      services6: "Team Strengthening",
      services7:
        "Design and facilitation of team building activities and development of effective teamwork.",
      services8: "Programs",
      services9:
        " Professional development programs and career plans for employees",
      services10: "Diversity and Inclusion",
      services11:
        "We offer tailored advice and solutions to create work environments where every individual feels valued and respected. From implementing inclusive policies to cultural awareness training, we work alongside your company to foster diversity and make the most of your team's talent.",
      services12: "Recruitment",
      services13:
        "Our team of human resources experts is dedicated to identifying and attracting the most suitable talent for your company. Through rigorous and personalized processes, we are committed to finding candidates who align perfectly with the needs and values of your organization. From active search to selection and hiring, our comprehensive approach ensures optimal results for your team",
      services14: "Workforce Optimization",
      services15:
        "Conducting employee satisfaction surveys and analyzing results to identify improvement opportunities within the company.",
      services16: "Empowering Companies",
      services17:
        " Offers expert human resources advice to drive the growth and efficiency of your organization. From recruitment strategies to optimizing staff performance, we work in collaboration with you to identify customized solutions that drive your business success.",
      services18: "Training",
      services19:
        "Our Training service provides training programs tailored to the specific needs of your team and industry.",
      services20: "Business Adaptation",
      services21:
        "Support in managing organizational change and resolving labor conflicts.",
      services22: "FemInnova",
      services23: "offers comprehensive services ",
      services24: "professional success",
      services30: "to drive ",
      services25:
        "From comprehensive recruitment processes to the implementation of specialized talent development workshops, we offer customized solutions to help our clients achieve their goals.",
      workshops1: "We help you ",
      workshops2: "enhance your professional profile ",
      workshops3: "to land a position that suits your needs.",
      workshops4: "Discover our talent services",
      workshops5: "LinkedIn Profile Workshop",
      workshops6:
        "You'll learn the best practices to optimize your LinkedIn profile and showcase your personal brand on the largest professional network in the market. You'll be able to create an attractive profile highlighting your skills, experience, and achievements, attracting recruiters' attention and job opportunities.",
      workshops7: "Stellar Professional Development Package",
      workshops8:
        "It offers a transformation of your CV and LinkedIn profile, along with a strategic job search session to enhance your brand and achieve your professional goals.",
      workshops9: "Customized CV and LinkedIn Workshop",
      workshops10:
        "Immerse yourself in a unique experience designed exclusively for you. You'll receive dedicated attention from our HR expert, who will guide you step by step to optimize your CV and LinkedIn profile, boosting your online presence and showcasing your skills to the job market.",
      workshops11: "CV Workshop",
      workshops12:
        "You'll learn the best practices to create an impactful Curriculum Vitae that highlights your skills and experience, and how to showcase your professional achievements to capture recruiters' attention.",
      workshops13: "Are you ready to ",
      workshops14: "take your career ",
      workshops15: "to the next level?",
      workshops16: "Complete the form and we'll get in touch.",
      workshops17: "Upload CV",
      workshops18: "Go Back",
      workshops19: "Name and Surname",
      workshops20: "Email",
      contact1: "Contact us",
      contact2: "Let's work together ",
      contact3: "to create a ",
      contact4: "culture of equal opportunities ",
      contact5: "for everyone, regardless of gender, race, or background.",
      contact6: "I am",
      contact7: "Talent",
      contact8: "Company",
      contact9: "Message",
      contact10: "Send",
      contact11: "Opening hours: 9 am to 5 pm",
      contact12: "Find us on our social media: ",

      },
    },
    es: {
      translation: {
        leading: "Liderando",
        transform:"la transformación del",
        talent2:"talento",
        parrapfPink:"Nos compremetemos a redefinir los estándares en",
        rrhh: "recursos humanos",
        diversity: " priorizando la diversidad",
        inclusion:" la inclusión y el ",
        talent:"desarrollo del talento",
        fundamentals:"como pilares fundamentales",
        mission:"Misión",
        mission2:"Nos dedicamos a diseñar y ejecutar estrategias de recursos humanos que valoran y promueven la diversidad y la inclusión. Nuestro compromiso es con el desarrollo del talento en su más amplia expresión, ofreciendo soluciones que permitan a las organizaciones y a sus equipos alcanzar su máximo potencial en un mercado laboral en constante evolución.",
        vision:"Visión",
        vision2:"Convertirnos en una firma global de recursos humanos que sea sinónimo de excelencia, innovación y equidad, estableciendo el estándar en la creación de entornos laborales inclusivos y dinámicos que celebren y potencien la diversidad en todas sus formas.",
        values:"Valores",
        values2:"Nuestros valores fundamentales incluyen la equidad, el respeto por la diversidad, la integridad, la innovación y la colaboración promoviendo la igualdad de oportunidades. Anticipamos tendencias para ofrecer servicios vanguardistas, y colaboramos estrechamente con nuestros clientes para impulsar el cambio positivo.",
        talent1:"Talentos",
        companies:"Empresas",
        femi:"FemInnova ",
        femi2:"innovación y calidad en la gestión del talento.",
        femi3:"Nuestra empresa, impulsada por una visión audaz, se compromete a redefinir los estándares en recursos humanos, priorizando la diversidad, la inclusión y el  desarrollo del talento como pilares fundamentales.",
        femi4:"destaca como un referente de",
        discover:"Descubre tu potencial con nuestros workshops especializados en",
        discover2:"desarrollo de talento",
        sendCv: "Enviar CV",
        home: "INICIO",
        services: "SERVICIOS",
        methodology: "METODOLOGÍA DE TRABAJO",
        contact: "CONTACTO",
        workshops: "WORKSHOPS",
        methodology2:"MetodologÍa de trabajo",
        mant:"Mantenemos un ",
        standard:"estándar de excelencia ",
        every:"en todos nuestros servicios, asegurando que cada estrategia esté ",
        align:"alineada con las necesidades y objetivos específicos",
        client:" de nuestros clientes.",
        how:"¿Cómo encontraremos a tu  candidato ideal?",
        Sourcing:"Sourcing",
        recolection:"Iniciamos el proceso de reclutamiento buscando candidatos potenciales en diversas fuentes, como bases de datos, redes sociales y referencias, para identificar a los mejores talentos que se ajusten a las necesidades del puesto.",
        groupEn:"Entrevista grupal",
        selection:"Selección del candidato",
        ofer:"Carta oferta",
        screening:"Screening telefónico",
        call:"Realizamos una primera evaluación de los candidatos a través de entrevistas telefónicas para verificar sus habilidades, experiencia y adecuación cultural con la empresa. Esto nos permite seleccionar a los candidatos más prometedores para avanzar en el proceso.",
        entrev:"Entrevista individual en profundidad utilizando técnica START: ",
        presentation:"Presentación al cliente",
        femContact:"En Feminnova , ",
        workHands:"trabajamos mano a mano ",
        clientEquip:"con nuestros clientes y sus equipos, creando sinergias que",
        positive:"impulsen un cambio positivo ",
        baseEqui:"en base a la equidad, igualdad y diversidad.",
        contactBotton:"Contactar",
        homeFooter: "Inicio",
        sendCvFooter:"Enviar CV",
        client2:" Clientes",
        servicesFooter:"Servicios",
        contactFooter:"Contacto",
        workshopsFooter:"Workshops",
        sendFooter:"Enviar",
        workMethodologyFooter:"Metodología de trabajo",
        reserved:"Todos los derechos reservados",
        preselection:"Invitamos a los candidatos preseleccionados a participar en entrevistas grupales, donde evaluamos su capacidad para trabajar en equipo, comunicarse efectivamente y resolver problemas en un entorno colaborativo.",
        tecnics:"Basándonos en las entrevistas y evaluaciones realizadas, seleccionamos a los candidatos más cualificados y adecuados para el puesto, teniendo en cuenta tanto sus habilidades técnicas como sus competencias personales.",
        help:"Una vez que el cliente ha seleccionado al candidato ideal, ayudamos en la elaboración de la carta de oferta, facilitando el proceso de contratación y asegurando una transición fluida hacia la incorporación del nuevo empleado.",
        start:"Llevamos a cabo entrevistas individuales detalladas utilizando la técnica START (Situación, Tarea, Acción, Resultado) para profundizar en la experiencia y habilidades de los candidatos, así como para evaluar su idoneidad para el puesto.",
        presentation2:"Presentamos a los candidatos seleccionados al cliente para su revisión y consideración final, proporcionando información detallada sobre cada candidato y su idoneidad para el puesto.",
        services1: "¿Listo para un ",
      services2: "cambio positivo",
      services3: " en la ",
      services4: "gestión del talento?",
      services5: "Nuestros servicios",
      services6: "Fortalecimiento de Equipos",
      services7:
        "Diseño y facilitación de actividades de team building y desarrollo de equipos de trabajo efectivos.",
      services8: "Programas",
      services9:
        " Programas de desarrollo profesional y planes de carrera para colaboradores",
      services10: "Diversidad e Inclusión",
      services11:
        "Ofrecemos asesoramiento y soluciones personalizadas para crear ambientes de trabajo donde cada individuo se sienta valorado y respetado. Desde la implementación de políticas inclusivas hasta la capacitación en conciencia cultural, trabajamos junto a su empresa para fomentar la diversidad y aprovechar al máximo el talento de su equipo.",
      services12: "Reclutamiento",
      services13:
        "Nuestro equipo de expertos en recursos humanos se encarga de identificar y atraer el talento más adecuado para su empresa. A través de procesos rigurosos y personalizados, nos comprometemos a encontrar candidatos que se alineen perfectamente con las necesidades y valores de su organización. Desde la búsqueda activa hasta la selección y contratación, nuestro enfoque integral garantiza resultados óptimos para su equipo",
      services14: "Optimización laboral",
      services15:
        "Realización de encuestas de clima laboral y análisis de resultados para identificar oportunidades de mejora en la empresa.",
      services16: "Potenciando Empresas",
      services17:
        " Ofrece asesoramiento experto en recursos humanos para impulsar el crecimiento y la eficiencia de su organización. Desde estrategias de reclutamiento hasta optimización del desempeño del personal, trabajamos en colaboración con usted para identificar soluciones personalizadas que impulsen su éxito empresarial.",
      services18: "Capacitaciones",
      services19:
        "Nuestro servicio de Capacitaciones brinda programas formativos adaptados a las necesidades específicas de su equipo y su industria.",
      services20: "Adaptación empresarial",
      services21:
        "Apoyo en la gestión del cambio organizacional y en la resolución de conflictos laborales.",
      services22: "FemInnova",
      services23: "ofrece servicios integrales ",
      services24: "éxito profesional",
      services25:
        "Desde la realización integral del proceso de reclutamiento hasta la implementación de talleres especializados en el desarrollo del talento, ofrecemos soluciones personalizadas para ayudar a nuestros clientes a alcanzar sus objetivos.",
      services30:"para impulsar el ",
        workshops1: "Te ayudamos a ",
      workshops2: "potenciar tu perfil profesional ",
      workshops3: "para alcanzar un puesto que se acomode a tus necesidades.",
      workshops4: "Conoce nuestros servicios para talento",
      workshops5: "Workshop de perfil de LinkedIn",
      workshops6:
        "Aprenderás las mejores prácticas para optimizar tu perfil de LinkedIn y destacar tu marca personal en la red profesional más grande del mercado. Podrás crear un perfil atractivo que resalte tus habilidades, experiencia y logros, atrayendo la atención de reclutadores y oportunidades laborales.",
      workshops7: "Paquete estelar de Desarrollo Profesional",
      workshops8:
        "Ofrece una transformación de tu CV y perfil de LinkedIn, junto con una sesión estratégica de búsqueda laboral para potenciar tu marca y alcanzar tus metas profesionales.",
      workshops9: "Taller personalizado de CV y LinkedIn",
      workshops10:
        "Sumérgete en una experiencia única diseñada exclusivamente para ti. Recibirás atención dedicada de nuestro experto en RRHH, quien te guiará paso a paso para optimizar tu CV y perfil de LinkedIn, impulsando tu presencia en línea y destacando tus habilidades ante el mundo laboral.",
      workshops11: "Workshop de CV",
      workshops12:
        "Aprenderás las mejores prácticas para crear un Currículum Vitae impactante que destaque tus habilidades y experiencia, y a resaltar tus logros profesionales para captar la atención de los reclutadores.",
      workshops13: "¿Estás listo para ",
      workshops14: "impulsar tu carrera ",
      workshops15: "al siguiente nivel?",
      workshops16: "Completa el formulario y nos pondremos en contacto.",
      workshops17: "Cargar CV",
      workshops18: "Click Devuelta",
      workshops19: "Nombre y apellido",
      workshops20: "Correo",
      contact1: "Contáctanos",
      contact2: "Trabajemos juntos ",
      contact3: "para crear una ",
      contact4: "cultura de igualdad de oportunidades ",
      contact5:
        "para todos, independientemente de género, raza o antecedentes.",
      contact6: "Soy",
      contact7: "Talento",
      contact8: "Empresa",
      contact9: "Mensaje",
      contact10: "Enviar",
      contact11: "Horario de atención: 9 a 17 h",
      contact12: "Te esperamos en nuestras redes sociales: ",
      },
    },
  };
  
  i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      resources,
      fallbackLng: 'en', // Idioma de respaldo en caso de que no se pueda determinar el idioma
      interpolation: {
        escapeValue: false, 
      },
      detection: {
        order: ['navigator', 'htmlTag'], // Define el orden de detección 
      },
    });
  
  export default i18n;
